### ISSUE TITLE
Insufficient terrorist checking

### ISSUE THREAD

**Issue by KittenOverflow** [seiyria/terrorist-checker#12]
Current checker only checks for the birth country of the visitor, but it has been scientifically proven that even some 'murican citizens can, and are willing to join ISIS.

http://www.nbcnewyork.com/news/local/Americans-ISIS-Double-in-Year-Terror-Recruiting-Concerns-Justice-Department-330005201.html

As such, I propose either rewording the question or falling back to the previous scheme and finding out a way to customize the 'ok' and 'cancel' buttons.

**Comment by seiyria** [comment]
I'm ok with both of these options (not both at once, though). Lets #keepTheInternetGreat.

**Comment by seiyria** [comment]
Thanks to @gytdau in #13 we're back to #keepingTheInternetGreat via the original "yes" and "no" mechanism. This will broaden the horizons for where terrorism can be found!
