### ISSUE TITLE
Loophole: Closing it will act as if pressed 'No'

### ISSUE THREAD

**Issue by gytdau** [seiyria/terrorist-checker#4]
![very nice image](http://i.imgur.com/FBOvPo0.gif)

As terrorists have a legal obligation to not say 'No' to this question, they can _instead_ just exit the dialog box and _**SHAZAM**_ they're let through to our precious 'Merican internet and just like that America is in ruins.

**Comment by seiyria** [comment]
Shit. You've defeated my ultimate-omega-alertcryption. Can someone please delete this issue so no one sees how to get around this bug? Please? This is bad news bears for america.

**Comment by gytdau** [comment]
I'm not a terrorist, please believe me
